/**
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost()
{
    m_Count = 0;
    m_CountIsSet = false;
    m_Cookie = utility::conversions::to_string_t("");
    m_CookieIsSet = false;
}

BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::~BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost()
{
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::validate()
{
    // TODO: implement validation
}

web::json::value BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_CountIsSet)
    {
        val[utility::conversions::to_string_t("count")] = ModelBase::toJson(m_Count);
    }
    if(m_CookieIsSet)
    {
        val[utility::conversions::to_string_t("cookie")] = ModelBase::toJson(m_Cookie);
    }

    return val;
}

bool BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("count")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("count"));
        if(!fieldValue.is_null())
        {
            int32_t refVal_count;
            ok &= ModelBase::fromJson(fieldValue, refVal_count);
            setCount(refVal_count);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("cookie")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("cookie"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_cookie;
            ok &= ModelBase::fromJson(fieldValue, refVal_cookie);
            setCookie(refVal_cookie);
        }
    }
    return ok;
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_CountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("count"), m_Count));
    }
    if(m_CookieIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("cookie"), m_Cookie));
    }
}

bool BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("count")))
    {
        int32_t refVal_count;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("count")), refVal_count );
        setCount(refVal_count);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("cookie")))
    {
        utility::string_t refVal_cookie;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("cookie")), refVal_cookie );
        setCookie(refVal_cookie);
    }
    return ok;
}

int32_t BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::getCount() const
{
    return m_Count;
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::setCount(int32_t value)
{
    m_Count = value;
    m_CountIsSet = true;
}

bool BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::countIsSet() const
{
    return m_CountIsSet;
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::unsetCount()
{
    m_CountIsSet = false;
}
utility::string_t BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::getCookie() const
{
    return m_Cookie;
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::setCookie(const utility::string_t& value)
{
    m_Cookie = value;
    m_CookieIsSet = true;
}

bool BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::cookieIsSet() const
{
    return m_CookieIsSet;
}

void BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost::unsetCookie()
{
    m_CookieIsSet = false;
}
}
}
}
}


