/**
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UserInfoResponseModel.h
 *
 * UserInfoResponseModel
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UserInfoResponseModel_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UserInfoResponseModel_H_


#include "../ModelBase.h"

#include "UserData.h"
#include "ApiKeyData.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// UserInfoResponseModel
/// </summary>
class  UserInfoResponseModel
    : public ModelBase
{
public:
    UserInfoResponseModel();
    virtual ~UserInfoResponseModel();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UserInfoResponseModel members

    /// <summary>
    /// Code，HTTP status code | HTTP状态码
    /// </summary>
    int32_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();

    void setCode(int32_t value);

    /// <summary>
    /// Router，The endpoint that generated this response | 生成此响应的端点
    /// </summary>
    utility::string_t getRouter() const;
    bool routerIsSet() const;
    void unsetRouter();

    void setRouter(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ApiKeyData> getApiKeyData() const;
    bool apiKeyDataIsSet() const;
    void unsetApi_key_data();

    void setApiKeyData(const std::shared_ptr<ApiKeyData>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UserData> getUserData() const;
    bool userDataIsSet() const;
    void unsetUser_data();

    void setUserData(const std::shared_ptr<UserData>& value);


protected:
    int32_t m_Code;
    bool m_CodeIsSet;
    utility::string_t m_Router;
    bool m_RouterIsSet;
    std::shared_ptr<ApiKeyData> m_Api_key_data;
    bool m_Api_key_dataIsSet;
    std::shared_ptr<UserData> m_User_data;
    bool m_User_dataIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UserInfoResponseModel_H_ */
