/**
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XBogusModel.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




XBogusModel::XBogusModel()
{
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_User_agent = utility::conversions::to_string_t("");
    m_User_agentIsSet = false;
}

XBogusModel::~XBogusModel()
{
}

void XBogusModel::validate()
{
    // TODO: implement validation
}

web::json::value XBogusModel::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UrlIsSet)
    {
        val[utility::conversions::to_string_t("url")] = ModelBase::toJson(m_Url);
    }
    if(m_User_agentIsSet)
    {
        val[utility::conversions::to_string_t("user_agent")] = ModelBase::toJson(m_User_agent);
    }

    return val;
}

bool XBogusModel::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("url")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("url"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_url;
            ok &= ModelBase::fromJson(fieldValue, refVal_url);
            setUrl(refVal_url);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("user_agent")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("user_agent"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_user_agent;
            ok &= ModelBase::fromJson(fieldValue, refVal_user_agent);
            setUserAgent(refVal_user_agent);
        }
    }
    return ok;
}

void XBogusModel::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("url"), m_Url));
    }
    if(m_User_agentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("user_agent"), m_User_agent));
    }
}

bool XBogusModel::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("url")))
    {
        utility::string_t refVal_url;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("url")), refVal_url );
        setUrl(refVal_url);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("user_agent")))
    {
        utility::string_t refVal_user_agent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("user_agent")), refVal_user_agent );
        setUserAgent(refVal_user_agent);
    }
    return ok;
}

utility::string_t XBogusModel::getUrl() const
{
    return m_Url;
}

void XBogusModel::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool XBogusModel::urlIsSet() const
{
    return m_UrlIsSet;
}

void XBogusModel::unsetUrl()
{
    m_UrlIsSet = false;
}
utility::string_t XBogusModel::getUserAgent() const
{
    return m_User_agent;
}

void XBogusModel::setUserAgent(const utility::string_t& value)
{
    m_User_agent = value;
    m_User_agentIsSet = true;
}

bool XBogusModel::userAgentIsSet() const
{
    return m_User_agentIsSet;
}

void XBogusModel::unsetUser_agent()
{
    m_User_agentIsSet = false;
}
}
}
}
}


