/**
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ToutiaoAppAPIApi.h
 *
 * 
 */

#ifndef IO_TIKHUB_CLIENT_API_ToutiaoAppAPIApi_H_
#define IO_TIKHUB_CLIENT_API_ToutiaoAppAPIApi_H_


#include "../ApiClient.h"

#include "HttpValidationError.h"
#include "ResponseModel.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace io {
namespace tikhub {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ToutiaoAppAPIApi 
{
public:

    explicit ToutiaoAppAPIApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ToutiaoAppAPIApi();

    /// <summary>
    /// 获取指定文章的信息/Get information of specified article
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7450114952884503059\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(
        utility::string_t groupId
    ) const;
    /// <summary>
    /// 获取指定文章的信息/Get information of specified article
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7450114952884503059\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_0(
        utility::string_t groupId
    ) const;
    /// <summary>
    /// 获取指定作品的评论/Get comments of specified post
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id &#x3D; \&quot;7453372680222523931\&quot; offset &#x3D; \&quot;0\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    /// <param name="offset">偏移量/Offset</param>
    pplx::task<std::shared_ptr<ResponseModel>> getCommentsApiV1ToutiaoAppGetCommentsGet(
        utility::string_t groupId,
        utility::string_t offset
    ) const;
    /// <summary>
    /// 获取指定作品的评论/Get comments of specified post
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id &#x3D; \&quot;7453372680222523931\&quot; offset &#x3D; \&quot;0\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    /// <param name="offset">偏移量/Offset</param>
    pplx::task<std::shared_ptr<ResponseModel>> getCommentsApiV1ToutiaoAppGetCommentsGet_0(
        utility::string_t groupId,
        utility::string_t offset
    ) const;
    /// <summary>
    /// 从头条用户主页获取用户user_id/Get user_id from user profile
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url &#x3D; \&quot;https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\&quot;
    /// </remarks>
    /// <param name="userProfileUrl">用户主页链接/User profile URL</param>
    pplx::task<std::shared_ptr<ResponseModel>> getUserIdApiV1ToutiaoAppGetUserIdGet(
        utility::string_t userProfileUrl
    ) const;
    /// <summary>
    /// 从头条用户主页获取用户user_id/Get user_id from user profile
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url &#x3D; \&quot;https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\&quot;
    /// </remarks>
    /// <param name="userProfileUrl">用户主页链接/User profile URL</param>
    pplx::task<std::shared_ptr<ResponseModel>> getUserIdApiV1ToutiaoAppGetUserIdGet_0(
        utility::string_t userProfileUrl
    ) const;
    /// <summary>
    /// 获取指定用户的信息/Get information of specified user
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### Return: - User information  # [示例/Example] user_id &#x3D; \&quot;1352838578180211\&quot;
    /// </remarks>
    /// <param name="userId">用户ID/User ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getUserInfoApiV1ToutiaoAppGetUserInfoGet(
        utility::string_t userId
    ) const;
    /// <summary>
    /// 获取指定用户的信息/Get information of specified user
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - &#x60;/api/v1/toutiao/app/get_user_id&#x60; ### Return: - User information  # [示例/Example] user_id &#x3D; \&quot;1352838578180211\&quot;
    /// </remarks>
    /// <param name="userId">用户ID/User ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getUserInfoApiV1ToutiaoAppGetUserInfoGet_0(
        utility::string_t userId
    ) const;
    /// <summary>
    /// 获取指定视频的信息/Get information of specified video
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7431543350882206242\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(
        utility::string_t groupId
    ) const;
    /// <summary>
    /// 获取指定视频的信息/Get information of specified video
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id &#x3D; \&quot;7431543350882206242\&quot;
    /// </remarks>
    /// <param name="groupId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_0(
        utility::string_t groupId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_TIKHUB_CLIENT_API_ToutiaoAppAPIApi_H_ */

