/**
 * TikHub.io - Your Ultimate Social Media Data & API Marketplace
 * High-performance asynchronous Douyin(抖音) TikTok Xiaohongshu(小红书) Kuaishou(快手) Weibo(微博) Instagram YouTube(油管) Twitter(X) Captcha Solver(验证码解决器) Temp Mail(临时邮箱) API(接口).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ToutiaoWebAPIApi.h
 *
 * 
 */

#ifndef IO_TIKHUB_CLIENT_API_ToutiaoWebAPIApi_H_
#define IO_TIKHUB_CLIENT_API_ToutiaoWebAPIApi_H_


#include "../ApiClient.h"

#include "HttpValidationError.h"
#include "ResponseModel.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace io {
namespace tikhub {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ToutiaoWebAPIApi 
{
public:

    explicit ToutiaoWebAPIApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ToutiaoWebAPIApi();

    /// <summary>
    /// 获取指定文章的信息/Get information of specified article
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id &#x3D; \&quot;7450114952884503059\&quot;
    /// </remarks>
    /// <param name="awemeId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(
        utility::string_t awemeId
    ) const;
    /// <summary>
    /// 获取指定文章的信息/Get information of specified article
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id &#x3D; \&quot;7450114952884503059\&quot;
    /// </remarks>
    /// <param name="awemeId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_0(
        utility::string_t awemeId
    ) const;
    /// <summary>
    /// 获取指定视频的信息/Get information of specified video
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id &#x3D; \&quot;7431543350882206242\&quot;
    /// </remarks>
    /// <param name="awemeId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(
        utility::string_t awemeId
    ) const;
    /// <summary>
    /// 获取指定视频的信息/Get information of specified video
    /// </summary>
    /// <remarks>
    /// # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id &#x3D; \&quot;7431543350882206242\&quot;
    /// </remarks>
    /// <param name="awemeId">作品ID/Post ID</param>
    pplx::task<std::shared_ptr<ResponseModel>> getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_0(
        utility::string_t awemeId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_TIKHUB_CLIENT_API_ToutiaoWebAPIApi_H_ */

